name = "typing-man"
main = "src/index.tsx"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "TYPING_MAN_KV"
id = "62d1c1d3c8fa4a2294cf4a2fb0446c94"

[build]
command = ""
